### ISSUE TITLE
Can't make patch for debian 4.9.0

### ISSUE THREAD

**Issue by SyRaza** [untangle/ngfw_kernels#1]
Not sure what's going on, I was able to make the patch last week but can't any longer. I keep getting this error.

```
[root @ untangle] ~/ngfw_kernels/debian-4.9.0 # make patch
dpkg-source -x linux_4.9.189-3.dsc
gpgv: unknown type of key resource 'trustedkeys.kbx'
gpgv: keyblock resource '/root/.gnupg/trustedkeys.kbx': General error
gpgv: Signature made Mon 02 Sep 2019 03:20:48 AM EDT
gpgv:                using RSA key 4644409808C171E05531DDEE054CB8F31343CF44
gpgv:                issuer "carnil@debian.org"
gpgv: Can't check signature: No public key
dpkg-source: warning: failed to verify signature on ./linux_4.9.189-3.dsc
dpkg-source: error: file ./linux_4.9.189.orig.tar.xz has size 471 instead of expected 94807908
Makefile:38: recipe for target 'extract-stamp' failed
make: *** [extract-stamp] Error 2
```

**Comment by sdelafond** [comment]
You got a corrupted/interrupted linux_4.9.189.orig.tar.xz during a previous download. Remove it and make download again. I've had it on my todo list for ages to verify checksums, so I should really get around to implementing it at some point.

**Comment by SyRaza** [comment]
I've created 4 different VMs and downloaded the file 6 different times (removed it twice and redownloaded). I keep getting this error. I simply use these commands

```
git clone https://github.com/untangle/ngfw_kernels
cd ~/ngfw_kernels/debian-4.9.0
make patch
```

Not sure how the download is corrupted 6 times. Any insights?

**Comment by sdelafond** [comment]
I'm told the S3 bucket holding those files is currently being moved to a new region:

```
cat  linux_4.9.189.orig.tar.xz                                                                                                                                                                                                                                              [seb hulk]
<html>
<head><title>400 Bad Request</title></head>
<body>
<h1>400 Bad Request</h1>
<ul>
<li>Code: IncorrectEndpoint</li>
<li>Message: The specified bucket exists in another region. Please direct requests to the specified endpoint.</li>
<li>Endpoint: download.untangle.com.s3-website-us-east-1.amazonaws.com</li>
<li>RequestId: 6D7727ADD8A28B4F</li>
<li>HostId: TzvxDJgsCeuRtsq8mGf++hAjbNqhnJSfx7IX+nhjOYbZhFgLOgl/PgldzC4Vkr4b5hHf1BsolD4=</li>
</ul>
<hr/>
</body>
</html>
```

It will be back shortly. In the meantime if you can't wait, just grab those two files from official Debian mirrors yourself.

**Comment by SyRaza** [comment]
Oh, perfect. I'll wait. Thank yo us much.

**Comment by sdelafond** [comment]
Let's keep this open until the bucket situation is fixed. Out of sheer curiosity, any reason you're not using the pre-built binary packages for that kernel ?

**Comment by SyRaza** [comment]
Just following a guide on dslreports to replace the ONT provided by my ISP, with my own untangle box. The guide calls for building the patch yourself. Here's the link to the [guide](https://www.dslreports.com/forum/r32399121-) if you'd like to have a look.

**Comment by sdelafond** [comment]
Gotcha, you also need *other* patches on top of the Untangle ones.
